# Project             :   Screenipy
# Author              :   Pranjal Joshi
# Created             :   27/04/2021
# Description         :   Workflow for CI - Testing source and PR main for release


name: Screenipy Build - Multi-arch Docker for Streamlit UI
on:
  push:
    branches: [ streamlit-ui ]
  pull_request:
    branches: [ streamlit-ui ]

jobs:

  Streamlit-Docker-Build:
  
    runs-on: ubuntu-latest

    # name: build for amd64/arm64
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: streamlit-ui
      
      # Setup hardware emulator using QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
      # Setup Docker Buildx for multi-arch images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Streamlit Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64, linux/arm64, linux/i386
        push: true
        tags: joshipranjal/screeni-py:gui